### ISSUE TITLE
Version in __version__

### ISSUE THREAD

**Issue by samuelgarcia** [mhhennig/HS2#49]
Hi Cole and Matthias.
Could you had a __version__ attributes in herdingspikes modules, so the version could be introspected from spikesorters ?

We need to report version for benchmark.

At the moment 
 ```python
spikesorters.print_sorter_version()
 ```
give 
```
herdingspikes: unknown
ironclust: 5.0.8
kilosort: unknown
kilosort2: unknown
klusta: 3.0.16
mountainsort4: unknown
spykingcircus: 0.9.0
tridesclous: 1.4.2
```

Cheers

Sam

**Comment by frozenblit** [comment]
Just a reminder, this should solve it but it's still waiting for a review: https://github.com/mhhennig/HS2/pull/47

**Comment by samuelgarcia** [comment]
https://github.com/MouseLand/Kilosort2/issues/182

https://github.com/magland/ml_ms4alg/issues/22

https://github.com/flatironinstitute/ironclust/issues/39

**Comment by samuelgarcia** [comment]
Cool. Thanks. it looks good to me but it is not my zone. :)

@colehurwitz @mhhennig could you review and merge ?

**Comment by colehurwitz** [comment]
@samuelgarcia Reviewed and merged! Thanks again @frozenblit for fixing this.

**Comment by frozenblit** [comment]
Nice. Thanks for merging it. ;)

**Comment by samuelgarcia** [comment]
cool!

**Comment by samuelgarcia** [comment]
```
herdingspikes: 0.3.3+git.f5232ac3520d
ironclust: 5.0.8
kilosort: unknown
kilosort2: unknown
klusta: 3.0.16
mountainsort4: unknown
spykingcircus: 0.9.0
tridesclous: 1.4.2
```
