### ISSUE TITLE
Run `HS2` without probe file

### ISSUE THREAD

**Issue by marcoistasy** [mhhennig/HS2#55]
Hello,

I am trying to sort data from [Behnke Fried](https://adtechmedical.com/depth-electrodes) contacts. However, the exact or even approximate geometry of the contacts is unable to be determined and so I am unable to run `HS2`. I am wondering if there is a workaround for this?

**Comment by mhhennig** [comment]
Just to point out that the latest HS version is now compatible with SpikeInterface >=0.90, where you can easily specify probe geometries. Get in touch with me if you need help!
