### ISSUE TITLE
Building wheel for herdingspikes (setup.py) ... error   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by ahmeddeladly** [mhhennig/HS2#57]
Hello,

I am trying to install herdingspikes package to use it in combination with SpikeInterface. Everytime I try to install herdingspikes using the pip install command, I get the above error.

Do you know what the issue is?

Thanks in advance

**Comment by mhhennig** [comment]
Hello @aeladly91, could you give a bit more detail about your setup so I can try to replicate this? Did you install spikeinterface with pip, and then herdingspieks with pip too?

**Comment by Virginia9733** [comment]
I have the same issue. When I create a conda env for spikeinterface, I tried to installed herdingspike in the environment, but got an error.

I first create a conda env python = 3.8, then installed requirements by pip: pip install -r requirements.txt
numpy
h5py
tqdm
click
pillow
scipy
matplotlib
seaborn
networkx
ipympl
scikit-learn
pyqt5
herdingspikes
jupyter
pyqtwebengine
pynwb
docker
probeinterface
spikeinterface[full]==0.90.1
phy==2.0b1

It failed with an error message:
![Screen Shot 2022-03-10 at 3 33 55 PM](https://user-images.githubusercontent.com/61534754/157611762-984275f5-11f5-4fe8-ada3-a1e5640d63cf.png)


Then installed herdingspikes by:
pip install numpy scipy
pip install herdingspikes

It failed with error: 
Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for herdingspikes
  Running setup.py clean for herdingspikes
Failed to build herdingspikes
Installing collected packages: herdingspikes
    Running setup.py install for herdingspikes ... error
![Screen Shot 2022-03-10 at 3 34 56 PM](https://user-images.githubusercontent.com/61534754/157611807-5c5ef2d1-1fcb-4ec8-8b3e-e45760a653be.png)

Looking forward to hearing from you!

**Comment by mhhennig** [comment]
I see, so @Virginia9733 , you are trying to install on Windows. Here you need to install the MS Visual Studio Build Tools first:
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017
We know the 2017 version works, hopefully more recent versions will also be ok.
Can you check if this helps?
@ahmeddeladly , do you have the same problem?
