### ISSUE TITLE
Version 0.3.100 fails at import

### ISSUE THREAD

**Issue by alejoe91** [mhhennig/HS2#58]
Hi guys, the new version fails at import in the spikeinterface tests with:
```
import herdingspikes as hs
../../../test_env/lib/python3.8/site-packages/herdingspikes/__init__.py:4: in <module>
    from herdingspikes.hs2 import HSDetection, HSClustering
../../../test_env/lib/python3.8/site-packages/herdingspikes/hs2.py:7: in <module>
    from .detection_localisation.detect import detectData
__init__.pxd:[19](https://github.com/SpikeInterface/spikeinterface/runs/5673855336?check_suite_focus=true#step:11:19)9: in init herdingspikes.detection_localisation.detect
    ???
E   ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 88, got 96
```

You can check the full log [here](https://github.com/SpikeInterface/spikeinterface/runs/5673855336?check_suite_focus=true)

**Comment by jonahpearl** [comment]
FWIW, this is now compounding with the removal of `np.bool`, which causes herdingspikes to fail (at least in the SI test run) for numpy versions 1.24 and above. So users with new SI installs will need to manually downgrade their pip to 1.22(.4?) to get HS working.

**Comment by mhhennig** [comment]
Ok thanks, will check!
