### ISSUE TITLE
Localization difference between BioCam and RecordingExtractor objects

### ISSUE THREAD

**Issue by BptGrm** [mhhennig/HS2#61]
Hi,
I'm trying to run Herding Spikes on an object that is then compatible with SpikeInterface and/or Neo objects.
Ideally, I would be able to have the flexibility of using standalone Herding Spikes while still being able to interact with a SpikeInterface pipeline.

My issue was intially detailed [here](https://github.com/SpikeInterface/spikeinterface/issues/728).

Essentially, running `HSDetection` on the same file with the same parameters results in different outputs depending on wether I use HS2's `BioCam` object or SI's `read_biocam` then feed it through `hs.probe.RecordingExtractor`, as illustrated [here](https://github.com/SpikeInterface/spikeinterface/issues/728#issuecomment-1161975819).

It seems to boil down to `BioCam` and `RecordingExtractor` having different default parameters for `inner_radius`, `neighbor_radius` and `masked_channels`, and using different files for position and neighbor coordinates.

As detailed [here](https://github.com/SpikeInterface/spikeinterface/issues/728#issuecomment-1164230771), the `neighbormatrix_spikeextractor` generated when using `RecordingExtractor` is very different from the default `neighbormatrix_biocam` used with `BioCam`, and as a result the `max_neighbors` property is different.

From what I've been able to understand, it might be caused by how channel positions are obtained [here](https://github.com/mhhennig/HS2/blob/7dd84c74cb4ad5ddefbc3740206d8cd06e68c382/herdingspikes/probe.py#L281).

**Comment by mhhennig** [comment]
Indeed, the parameters set in the probe differ. It's been the plan for some time to only use SpikeImterface objects, but progress has been a bit slow to implement this. Do you think you can adjust the parameters to get the same behaviour? I'll take a closer look asap!

**Comment by BptGrm** [comment]
I have already tried passing the arguments with `Probe = hs.probe.RecordingExtractor(recording,noise_amp_percent=1,inner_radius=1.75,neighbor_radius=None, masked_channels=[0])`, but the `max_neighbors` property remains different because `BioCam` uses preset [file](https://github.com/mhhennig/HS2/blob/master/herdingspikes/probe_info/neighbormatrix_biocam) for its neighbors matrix, while `RecordingExtractor` [generates a new file](https://github.com/mhhennig/HS2/blob/72b19a03917f00fb4d160167b82eefe2169fdc4f/herdingspikes/probe.py#L297) on the go that is very different from the base BioCam neighbors matrix (see attached file [here](https://github.com/SpikeInterface/spikeinterface/issues/728#issuecomment-1164230771)).

**Comment by BptGrm** [comment]
I compared results from the same file, using the same parameters, with the only difference being that one is loaded through `Probe = BioCam(file_path)` and the other through SpikeInterface's `read_biocam`, as `recording = read_biocam(file_path)` then `Probe = hs.probe.RecordingExtractor(recording)`.

Sorting and clustering are then performed with the exact same parameters. 

The first obvious difference is when using `H.PlotTracesChannel` : 
Through HS : 
![HS2_PlotTracesChannel](https://user-images.githubusercontent.com/83828302/186670068-9ec4c570-06b5-4b95-b876-e6b19722aba3.png)
Through SI : 
![SI2_PlotTracesChannel](https://user-images.githubusercontent.com/83828302/186670183-f33a8bec-2202-4aa2-9f27-d8671b9b049c.png)

Then, with `H.PlotAll` : 
Through HS : 
![HS2_PlotAll](https://user-images.githubusercontent.com/83828302/186670374-18601049-e5c0-4b97-b01f-60bdc53372e1.png)
Through SI : 
![SI2_PlotAll](https://user-images.githubusercontent.com/83828302/186670428-a629912b-b235-4cae-8ebf-717140a97070.png)

The main difference is that it's rotated and mirrored, but there's also slightly fewer spikes detected : 59742 spikes through HS and 60990 spikes through SI. Again, all of the detection parameters are exactly the same, the only difference is the `Probe` object. 

This is also the case after clustering, with `C.PlotAll` : 
Through HS : 
![HS2_C_PlotAll](https://user-images.githubusercontent.com/83828302/186671058-8a47e51e-66bf-4201-b942-bf7bd87eccfc.png)
Through SI : 
![SI2_C_PlotAll](https://user-images.githubusercontent.com/83828302/186671181-76025cb6-74c4-4ab1-a712-72910aa8e94f.png)

The axis labels are also incorrect when going through SI's reader.

From what I can tell, it seems to stem from `BioCam` `Probe` objects getting their positions and neighbours coordinates from `positions_biocam` and `neighbormatrix_biocam`, respectively, while the `RecordingExtractor` `Probe` object uses `positions_spikeextractor` and `neighbormatrix_spikeextractor`, which seem quite different.

@mhhennig Is there a reason why those objects need to use different coordinate files ?

**Comment by BptGrm** [comment]
See #70
