### ISSUE TITLE
Cant run herdingspikes

### ISSUE THREAD

**Issue by franciscomiqueles** [mhhennig/HS2#64]
Hello, 

I have been testing Spikeinterface using the tutorials in the github. I tried to sort through herdingspikes using the database provided in the tutorial but i have the following error in the code

`sorting_HS = ss.run_herdingspikes(recording_loaded, output_folder='results_HS', 
                                  filter=False, verbose=True)
print('Found', len(sorting_HS.get_unit_ids()), 'units')`

 Generating new position and neighbor files from data file
 Not Masking any Channels
 Sampling rate: 20000
 Localization On
 Number of recorded channels: 16
 Few recording channels: not subtracing mean from activity
 Analysing frames: 6000000; Seconds: 300.0
 Frames before spike in cutout: 6
 Frames after spike in cutout: 36
 tcuts: 26 56
 tInc: 100000
 Detection completed, time taken: 0:00:00.854102
 Time per frame: 0:00:00.000142
 Time per sample: 0:00:00.000009
Loaded 0 spikes.
Error running herdingspikes
Traceback (most recent call last):
  File "/home/brontodegus/anaconda3/envs/si090/lib/python3.8/site-packages/spikeinterface/sorters/basesorter.py", line 200, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "/home/brontodegus/anaconda3/envs/si090/lib/python3.8/site-packages/spikeinterface/sorters/herdingspikes/herdingspikes.py", line 226, in _run_from_folder
    uids = C.spikes.cl.unique()
  File "/home/brontodegus/anaconda3/envs/si090/lib/python3.8/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'cl'

Also, i tried changing "filter=True" but i still having the same error .

Thanks for your help.

**Comment by nasnass** [comment]
Hi! Were you able to find a solution - I am currently also struggling running herdingspikes on SI

**Comment by BptGrm** [comment]
As you can see here : `Loaded 0 spikes.`, it seems HS2 found zero spikes. Since the `C.spikes` DataFrame is most likely empty, HS2 failed.
Either there is something with your raw or processed data, or the detection threshold is too high.

**Comment by mhhennig** [comment]
Correct, this means no spikes were detected (falsely leads to an error, this is internal to HS as it then tries to extract features). Is this still an issue?
