### ISSUE TITLE
Kernel died when using herdingspikes in SpikeInterface

### ISSUE THREAD

**Issue by betty6you** [mhhennig/HS2#68]
Hi,
I have installed herdingspikes to run spike sorting in SpikeInterface, but it will cause the kernel died everytime I do it.

What will be the problem in my code?
Here is the code: https://github.com/betty6you/EDFRecordingExtractor/blob/main/EDF_extractor_test_1.ipynb

Hope you can help me solve it.

Many thanks.

**Comment by mhhennig** [comment]
Hi, sorry for the long delay. It's difficult to say why this fails, but I suspect it has to do with the probe geometry - Herding Spikes uses multiple channels to estimate spike locations, and in your case channels seem separated by 100um (?). So the localisation method has no data to work with and will thus fail (it's not expected though that the kernel dies). I think HS is not right for your data, here other sorters such as MountainSort may perform much better.

**Comment by betty6you** [comment]
Thanks for your reply. I will try other method then.

Sent from my iPhone

On Mar 9, 2023, at 3:38 PM, Matthias H. Hennig ***@***.***> wrote:

﻿

Hi, sorry for the long delay. It's difficult to say why this fails, but I suspect it has to do with the probe geometry - Herding Spikes uses multiple channels to estimate spike locations, and in your case channels seem separated by 100um (?). So the localisation method has no data to work with and will thus fail (it's not expected though that the kernel dies). I think HS is not right for your data, here other sorters such as MountainSort may perform much better.
