### ISSUE TITLE
SpikeInterface CMR vs integrated CMR

### ISSUE THREAD

**Issue by b-grimaud** [mhhennig/HS2#75]
Hi,

I was wondering wether the integrated CMR/CAR has better performance than the one included in SpikeInterface since it's handled by the C part of the code.

I typically use the chained preprocessing pipeline of SI with unsigned to signed -> bandpass -> CMR for BioCAM recordings but I assume that a redundant CMR is probably less than optimal.

From what I can gather in `detect.pyx` :
```
self.median_reference = common_reference == "median"
self.average_reference = common_reference == "average"
```
If `"common_reference"` is anything else than `"average"` or `"median"` no referencing will happen ?

I was also wondering if the default -1280 rescaling helps with detection in any way.

Thanks !

**Comment by mhhennig** [comment]
The new version performs a median-based CMR that is quite fast (both mean and median is implemented, but mean is just too suscpetible to outliers). There's therefore no need to use the SpikeInterface filter. It's also not probably necessary to use any low/bandpass filter as the C++ code implements a simple filter that works well (not tested extensively yet).

**Comment by b-grimaud** [comment]
I'll run both and try to get some profiling done, thanks !
