### ISSUE TITLE
Why only Python>=3.12?

### ISSUE THREAD

**Issue by alejoe91** [mhhennig/HS2#82]
Hi @mhhennig 

Is there a reason for the `python-requires>=3.12`?

Can't install this anywhere on our cloud-deployed machines :(

**Comment by mhhennig** [comment]
The version here is already >=3.10. Just uploaded 0.4.4 to pypi, does it work now?

**Comment by alejoe91** [comment]
I'll try :)

**Comment by alejoe91** [comment]
Nope.. this is the problem: https://github.com/mhhennig/HS2/blob/master/setup.py#L157

**Comment by mhhennig** [comment]
Allright, but now! 🙄

**Comment by mhhennig** [comment]
🎉
